# Generated by Django 5.0.6 on 2024-05-21 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_agency', '0002_remove_tour_aircategory_aircategory_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aircategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='aircategory',
            name='price',
        ),
        migrations.AddField(
            model_name='tour',
            name='aircategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='aircategory', to='tour_agency.aircategory'),
            preserve_default=False,
        ),
    ]
